apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting-rules
  namespace: observability
  labels:
    grafana_alert: "1"
data:
  loki-alerts.yaml: |
    apiVersion: 1
    groups:
      - orgId: 1
        name: loki-alerts
        folder: Alerts
        interval: 1m
        rules:
          - uid: logs-error-burst
            title: LogsErrorBurst
            condition: B
            data:
              - refId: A
                relativeTimeRange:
                  from: 300
                  to: 0
                datasourceUid: P8E80F9AEF21F6940
                model:
                  expr: "sum by (app, route, version) (count_over_time({namespace=\"apps\"} |~ `\"status\":5[0-9]{2}` | regexp `\"route\":\"(?P<route>[^\"]+)\"` [5m]))"
                  refId: A
              - refId: B
                relativeTimeRange:
                  from: 300
                  to: 0
                datasourceUid: __expr__
                model:
                  type: threshold
                  expression: A
                  conditions:
                    - evaluator:
                        type: gt
                        params:
                          - 10
                      operator:
                        type: and
                      reducer:
                        type: last
                  refId: B
            for: 5m
            labels:
              severity: warning
              team: backend
              env: development
              service: available-schedules
            annotations:
              summary: "Alta taxa de erros 5xx"
              description: "Mais de 10 erros 5xx nos ultimos 5 minutos."