apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-rules
  namespace: observability
  labels:
    loki_rule: "true"
data:
  rules.yaml: |
    groups:
      - name: logs.errors
        rules:
          - alert: LogsErrorBurst
            expr: |
              sum by (app) (
                count_over_time(
                  {namespace="apps"} |~ "level.*error" [5m]
                )
              ) > 5
            for: 1m
            labels:
              severity: ticket
              team: sre
              env: dev
            annotations:
              summary: "Explosão de logs de erro em {{ $labels.app }}"
              description: "Mais de 5 logs com level=error nos últimos 5 minutos"
              runbook_url: "runbooks/erro-5xx.md"
