apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-debugger
  namespace: observability
  labels: { app: alert-debugger }
spec:
  replicas: 1
  selector:
    matchLabels: { app: alert-debugger }
  template:
    metadata:
      labels: { app: alert-debugger }
    spec:
      containers:
        - name: echo
          image: mendhak/http-https-echo:31
          env:
            - name: HTTP_PORT
              value: "8080"
            - name: LOG_WITHOUT_NEWLINE
              value: "true"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: alert-debugger
  namespace: observability
spec:
  selector: { app: alert-debugger }
  ports:
    - port: 8080
      targetPort: 8080