apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: orders-api
  labels:
    release: kps   # deve casar com o release do kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: orders-api
  namespaceSelector:
    matchNames: [ "apps" ]
  endpoints:
    - port: http
      path: /metrics
      interval: 15s